spring.application.name=server
server.servlet.context-path=/api

# secret
spring.config.import=optional:application-secret.properties

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# DB
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# KST
spring.jackson.time-zone=Asia/Seoul

# GPT
openai.key=${OPENAI_KEY}
openai.timeout=${OPENAI_TIMEOUT}

# S3
access-key=${ACCESS_KEY}
secret-key=${SECRET_KEY}
bucket-name=${BUCKET_NAME}
region=ap-northeast-2
# 파일 하나 최대 용량
spring.servlet.multipart.max-file-size=8MB
# 한 요청에서 총 업로드 허용 용량
spring.servlet.multipart.max-request-size=8MB