spring.application.name=server
server.servlet.context-path=/api

# secret
spring.config.import=optional:application-secret.properties

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# DB
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# KST
spring.jackson.time-zone=Asia/Seoul

# GPT
openai.key=${OPENAI_KEY}
openai.timeout=${OPENAI_TIMEOUT}
